services:
  aniscrape:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: aniscrape
    restart: unless-stopped
    volumes:
      - ../storage:/app/storage
      - ../logs:/app/logs
      - ../config.yaml:/app/config.yaml